Transform: 'AWS::Serverless-2016-10-31'
Description: >
  SAM Template for Weekly_Pocket_Readtime_Tagger function. Includes function and cron schedule.
Resources:
  Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Weekly_Pocket_Readtime_Tagger
      Description: >
        Lambda function which tags unread articles (saved in the last 7 days) in my Pocket based on read-time.
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 300
      Policies:
        - SecretsManagerReadWrite
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Name: WeeklySundayTwoPm
            Schedule: cron(0 14 ? * SUN *)
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pocket-readtime-tagger-layer
      Description: Lambda layer with libs like pocket and datetime
      ContentUri: ../libs